/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  welcome: [
    'main-stuff/welcome/README',
    'main-stuff/welcome/what-is-athens-research/README',
    'main-stuff/welcome/what-is-athens-research/vision',
    'main-stuff/welcome/what-is-athens-research/why-athens'
  ],
  athens: [
    {
      type: 'autogenerated', 
      dirName: 'main-stuff/using-athens-product'
    }
  ],
  athensResearch: [
    {
      type: 'autogenerated', 
      dirName: 'main-stuff/athens-research-governance-and-operations'
    }
  ],
  contribute: [
    'main-stuff/contributing'
  ],
  academy: [
    {
      type: 'autogenerated', 
      dirName: 'main-stuff/learning-at-athens-academy-education'
    }
  ],
  help: [
    'help/contact-us'
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
